In [1]:
import nfl_data_py as nfl
import pandas as pd
import numpy as np

In [2]:
# pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df = nfl.import_pbp_data([2024])

2024 done.
Downcasting floats.

In [4]:
game = df.loc[df['game_id']=="2024_20_BAL_BUF"].copy()
game

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
48252,1.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,None,None,None,...,0.0,0.0,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48253,39.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BAL,away,BUF,...,0.0,0.0,0.143454,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48254,62.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BAL,away,BUF,...,0.0,0.0,-0.595957,NaN,NaN,NaN,NaN,NaN,0.468283,-46.828278
48255,84.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BAL,away,BUF,...,0.0,0.0,-0.550132,NaN,NaN,NaN,NaN,NaN,0.663315,-66.331459
48256,106.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BAL,away,BUF,...,0.0,0.0,1.911900,NaN,NaN,NaN,NaN,NaN,0.982585,1.741505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48405,3767.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BUF,home,BAL,...,0.0,0.0,0.135715,NaN,NaN,NaN,NaN,NaN,0.056761,-5.676054
48406,3806.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,None,None,None,...,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48407,3794.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BUF,home,BAL,...,0.0,0.0,-0.377236,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48408,3823.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BUF,home,BAL,...,0.0,0.0,-1.757979,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48409,3845.0,2024_20_BAL_BUF,2025011901,BUF,BAL,POST,20,BUF,home,BAL,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
def game_epa(game):
    # remove posteam of None, epa NaN, which should catch start, end, timeouts
    home_team = game['home_team'].values[0]
    away_team = game['away_team'].values[0]
    # epa = pd.DataFrame(index=[home_team, away_team])

    df = game.groupby(['posteam', 'play_type']).agg({'epa': sum})
    home_epa = df.loc[home_team] - df.loc[away_team]
    home_epa.rename(columns={'epa': home_team}, inplace=True)
    away_epa = df.loc[away_team] - df.loc[home_team]
    away_epa.rename(columns={'epa': away_team}, inplace=True)
    epa = pd.concat([home_epa, away_epa], axis=1) # figure out how to use keys, names, levels to get the naming correct. epa at the top of the hierarchy, then team names for the ind. columns. instead of the renaming

    return(epa)

In [57]:
game_epa(game)

                  BUF       BAL
play_type
extra_point  0.135146 -0.135146
field_goal   0.558461 -0.558461
kickoff      2.264385 -2.264385
no_play      2.600836 -2.600836
pass        -1.041243  1.041243
punt              NaN       NaN
qb_kneel    -2.135215  2.135215
run         -2.646128  2.646128