In [2]:
import nfl_data_py as nfl
import pandas as pd
import numpy as np

In [3]:
# pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [13]:
df = nfl.import_pbp_data([2024])
df

2024 done.
Downcasting floats.

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,None,None,None,...,0.0,0.0,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,0.257819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,61.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,-0.200602,NaN,NaN,NaN,NaN,NaN,0.456761,-45.676102
3,83.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,2.028874,1.345418,9.321221,8.0,0.509778,0.363807,0.576656,42.334431
4,108.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,0.754242,0.882798,5.783560,4.0,0.668478,0.255140,0.426443,57.355690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49311,4718.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,WAS,away,PHI,...,0.0,0.0,-0.722550,NaN,NaN,NaN,NaN,NaN,0.949295,-94.929489
49312,4747.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,WAS,away,PHI,...,0.0,0.0,-2.747494,NaN,NaN,NaN,NaN,NaN,0.930013,-93.001251
49313,4769.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,PHI,home,WAS,...,0.0,0.0,-0.650122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49314,4791.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,PHI,home,WAS,...,0.0,0.0,-2.106240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49315,4813.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,PHI,home,WAS,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
game = df.loc[df['game_id']=="2024_21_WAS_PHI"].copy()
game.drop(game[game['posteam'].isna()].index, inplace=True)
game.drop(game[game['epa'].isna()].index, inplace=True)
columns = ['posteam','time','qtr','down','ydstogo','yrdln','play_type','desc','ep','epa','total_home_epa','total_away_epa']
game[columns]

,posteam,time,qtr,down,ydstogo,yrdln,play_type,desc,ep,epa,total_home_epa,total_away_epa
49118,WAS,15:00,1.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 65 yards from PHI 35 to end zone, Touchback to the WAS 30.",0.770222,0.257819,-0.257819,0.257819
49119,WAS,15:00,1.0,1.0,10.0,WAS 30,run,(15:00) (Shotgun) 5-J.Daniels scrambles up the middle to WAS 31 for 1 yard (3-N.Smith; 90-J.Davis).,1.028041,-0.443009,0.185190,-0.185190
49120,WAS,14:25,1.0,2.0,9.0,WAS 31,pass,"(14:25) (No Huddle, Shotgun) 5-J.Daniels pass short right to 86-Z.Ertz to WAS 34 for 3 yards (2-D.Slay).",0.585033,-0.398863,0.584053,-0.584053
49121,WAS,13:52,1.0,3.0,6.0,WAS 34,pass,"(13:52) (No Huddle, Shotgun) 5-J.Daniels pass short left to 17-T.McLaurin to WAS 41 for 7 yards (27-Q.Mitchell).",0.186169,1.697098,-1.113045,1.113045
49122,WAS,13:31,1.0,1.0,10.0,WAS 41,pass,"(13:31) (No Huddle, Shotgun) 5-J.Daniels pass incomplete short middle to 30-A.Ekeler (93-M.Williams).",1.883267,-0.513502,-0.599543,0.599543
...,...,...,...,...,...,...,...,...,...,...,...,...
49310,WAS,02:24,4.0,2.0,7.0,WAS 33,run,(2:24) (Shotgun) 30-A.Ekeler up the middle to WAS 36 for 3 yards (58-J.Hunt).,0.944009,-0.230327,32.635559,-32.635559
49311,WAS,02:00,4.0,3.0,4.0,WAS 36,run,(2:00) (Shotgun) 30-A.Ekeler up the middle to WAS 37 for 1 yard (43-N.Morrow).,0.713683,-0.722550,33.358109,-33.358109
49312,WAS,01:20,4.0,4.0,3.0,WAS 37,run,(1:20) (Shotgun) 30-A.Ekeler up the middle to WAS 37 for no gain (97-M.Ojomo).,-0.008868,-2.747494,36.105602,-36.105602
49313,PHI,01:14,4.0,1.0,10.0,WAS 37,qb_kneel,(1:14) 7-K.Pickett kneels to WAS 39 for -2 yards.,2.756362,-0.650122,35.455479,-35.455479
49314,PHI,00:34,4.0,2.0,12.0,WAS 39,qb_kneel,(:34) 7-K.Pickett kneels to WAS 40 for -1 yards.,2.106240,-2.106240,33.349239,-33.349239

In [23]:
game.loc[game['play_type']=='extra_point', columns]

,posteam,time,qtr,down,ydstogo,yrdln,play_type,desc,ep,epa,total_home_epa,total_away_epa
49139,PHI,07:39,1.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,3.431164,-3.431164
49151,PHI,03:43,1.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,11.364073,-11.364073
49212,PHI,00:39,2.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,14.917247,-14.917247
49237,PHI,08:58,3.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,17.793377,-17.793377
49272,PHI,12:24,4.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,16.268209,-16.268209
49287,PHI,07:58,4.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,24.333620,-24.333620
49307,PHI,03:03,4.0,NaN,0.0,WAS 15,extra_point,"4-J.Elliott extra point is GOOD, Center-49-R.Lovato, Holder-10-B.Mann.",0.932427,0.067573,32.522980,-32.522980

In [15]:
def game_epa(game):
    # remove posteam None, epa NaN. should catch start, end, timeouts
    game.drop(game[game['posteam'].isna()].index, inplace=True)
    game.drop(game[game['epa'].isna()].index, inplace=True)

    # TODO: fillna with 0, so if a team didn't do a certain play type, the NaN doesn't pollute the results
    home_team = game['home_team'].values[0]
    away_team = game['away_team'].values[0]
    # epa = pd.DataFrame(index=[home_team, away_team])

    df = game.groupby(['posteam', 'play_type']).agg({'epa': sum})
    home_epa = df.loc[home_team] - df.loc[away_team]
    home_epa.rename(columns={'epa': home_team}, inplace=True)
    away_epa = df.loc[away_team] - df.loc[home_team]
    away_epa.rename(columns={'epa': away_team}, inplace=True)
    epa = pd.concat([home_epa, away_epa], axis=1) # figure out how to use keys, names, levels to get the naming correct. epa at the top of the hierarchy, then team names for the ind. columns. instead of the renaming

    return(epa)

In [16]:
game_epa(game)

                   PHI        WAS
play_type
extra_point        NaN        NaN
field_goal   -5.113410   5.113410
kickoff       4.623072  -4.623072
no_play       3.758110  -3.758110
pass         21.878645 -21.878645
punt         -0.560571   0.560571
qb_kneel           NaN        NaN
run          11.046744 -11.046744

In [24]:
game.loc[game['play_type']=='kickoff', columns]

,posteam,time,qtr,down,ydstogo,yrdln,play_type,desc,ep,epa,total_home_epa,total_away_epa
49118,WAS,15:00,1.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 65 yards from PHI 35 to end zone, Touchback to the WAS 30.",0.770222,0.257819,-0.257819,0.257819
49137,PHI,07:57,1.0,NaN,0.0,WAS 35,kickoff,47-Z.Gonzalez kicks 60 yards from WAS 35 to PHI 5. 28-W.Shipley to PHI 40 for 35 yards (20-Q.Martin).,1.406632,0.934535,-1.295242,1.295242
49140,WAS,07:39,1.0,NaN,0.0,PHI 35,kickoff,4-J.Elliott kicks 61 yards from PHI 35 to WAS 4. 12-L.McCaffrey to WAS 27 for 23 yards (58-J.Hunt).,0.865336,0.095965,3.335199,-3.335199
49152,WAS,03:43,1.0,NaN,0.0,PHI 35,kickoff,4-J.Elliott kicks 64 yards from PHI 35 to WAS 1. 12-L.McCaffrey to WAS 27 for 26 yards (21-S.Brown; 36-T.McCollum).,0.870265,0.092399,11.271674,-11.271674
49164,PHI,14:42,2.0,NaN,0.0,WAS 35,kickoff,47-Z.Gonzalez kicks 61 yards from WAS 35 to PHI 4. 28-W.Shipley to PHI 29 for 25 yards (11-J.Chinn).,1.190974,0.290711,9.525048,-9.525048
49185,PHI,07:05,2.0,NaN,0.0,WAS 35,kickoff,"47-Z.Gonzalez kicks 60 yards from WAS 35 to PHI 5. 14-K.Gainwell MUFFS catch, and recovers at PHI 8. 14-K.Gainwell to PHI 28 for 20 yards (38-K.Seymour; 22-D.Forrest).",0.883158,0.075667,2.066031,-2.066031
49202,WAS,01:44,2.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 60 yards from PHI 35 to WAS 5. 26-J.McNichols to WAS 22 for 17 yards (28-W.Shipley). FUMBLES (28-W.Shipley), touched at WAS 22, RECOVERED by PHI-14-K.Gainwell at WAS 24.",0.689469,-4.469679,11.629885,-11.629885
49213,WAS,00:39,2.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 65 yards from PHI 35 to end zone, Touchback to the WAS 30.",0.283147,0.059681,14.857567,-14.857567
49222,PHI,00:02,2.0,NaN,0.0,WAS 35,kickoff,47-Z.Gonzalez kicks 66 yards from WAS 35 to PHI -1. 14-K.Gainwell to PHI 18 for 19 yards (35-P.Butler).,0.000492,-0.000492,12.199902,-12.199902
49224,PHI,15:00,3.0,NaN,0.0,WAS 35,kickoff,47-Z.Gonzalez kicks 62 yards from WAS 35 to PHI 3. 28-W.Shipley to PHI 31 for 28 yards (32-M.Walker). PHI-14-K.Gainwell was injured during the play.,1.474098,0.370569,12.570471,-12.570471
49238,WAS,08:58,3.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 65 yards from PHI 35 to end zone, Touchback to the WAS 30.",0.867975,0.292741,17.500635,-17.500635
49248,PHI,05:01,3.0,NaN,0.0,WAS 35,kickoff,47-Z.Gonzalez kicks 58 yards from WAS 35 to PHI 7. 34-I.Rodgers pushed ob at PHI 31 for 24 yards (11-J.Chinn; 22-D.Forrest).,1.407715,0.365322,10.973675,-10.973675
49273,WAS,12:24,4.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 65 yards from PHI 35 to end zone, Touchback to the WAS 30.",0.997838,0.256099,16.012112,-16.012112
49288,WAS,07:58,4.0,NaN,0.0,PHI 35,kickoff,4-J.Elliott kicks 62 yards from PHI 35 to WAS 3. 30-A.Ekeler to WAS 35 for 32 yards (54-J.Trotter).,1.121784,0.477888,23.855734,-23.855734
49308,WAS,03:03,4.0,NaN,0.0,PHI 35,kickoff,"4-J.Elliott kicks 65 yards from PHI 35 to end zone, Touchback to the WAS 30.",0.826262,0.350329,32.172649,-32.172649