In [3]:
import nfl_data_py as nfl

In [4]:
data = nfl.import_pbp_data([2024])

2024 done.
Downcasting floats.

In [6]:
data

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,None,None,None,...,0.0,0.0,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,0.257819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,61.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,-0.200602,NaN,NaN,NaN,NaN,NaN,0.456761,-45.676102
3,83.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,2.028874,1.345418,9.321221,8.0,0.509778,0.363807,0.576656,42.334431
4,108.0,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0.0,0.0,0.754242,0.882798,5.783560,4.0,0.668478,0.255140,0.426443,57.355690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49311,4718.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,WAS,away,PHI,...,0.0,0.0,-0.722550,NaN,NaN,NaN,NaN,NaN,0.949295,-94.929489
49312,4747.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,WAS,away,PHI,...,0.0,0.0,-2.747494,NaN,NaN,NaN,NaN,NaN,0.930013,-93.001251
49313,4769.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,PHI,home,WAS,...,0.0,0.0,-0.650122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49314,4791.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,PHI,home,WAS,...,0.0,0.0,-2.106240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49315,4813.0,2024_21_WAS_PHI,2025012600,PHI,WAS,POST,21,PHI,home,WAS,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.loc[]